---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: catalogserver-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: catalogserver-ca
  namespace: system
spec:
  isCA: true
  secretName: catalogd-catalogserver-ca
  dnsNames:
    - catalogd.io
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: catalogd-catalogserver-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: catalogserver-ca-issuer
  namespace: system
spec:
  ca:
    secretName: catalogd-catalogserver-ca