resources:
- ../../base/default
- resources

patches:
- target:
    kind: Service
    name: catalogserver
  path: patches/catalogserver_service_port.yaml
- target:
    kind: Deployment
    name: controller-manager
  path: patches/manager_deployment_certs.yaml