apiVersion: v1
kind: Service
metadata:
  labels:
      app.kubernetes.io/part-of: olm
      app.kubernetes.io/name: catalogd
  name: catalogserver
  namespace: system
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8083
