apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: olm
    app.kubernetes.io/name: catalogd
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/part-of: olm
    app.kubernetes.io/name: catalogd
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                    - ppc64le
                    - s390x
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: kube-rbac-proxy
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --http2-disable
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        ports:
        - containerPort: 8443
          protocol: TCP
          name: https
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
        terminationMessagePolicy: FallbackToLogsOnError
      - command:
        - ./manager
        args:
        - --leader-elect
        - --metrics-bind-address=127.0.0.1:8080
        - --http-external-address=http://catalogd-catalogserver.catalogd-system.svc
        image: controller:latest
        name: manager
        volumeMounts:
            - name: cache
              mountPath: /var/cache/
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 1000m
            memory: 200Mi
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cache
          emptyDir: {}
