---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: catalogserver-cert
  namespace: system
spec:
  secretName: catalogd-catalogserver-cert-git-version
  dnsNames:
    - localhost
    - catalogd-catalogserver.olmv1-system.svc
    - catalogd-webhook-service.olmv1-system.svc
    - catalogd-catalogserver.olmv1-system.svc.cluster.local
    - catalogd-webhook-service.olmv1-system.svc.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: olmv1-ca
