apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalogd-ingress
  namespace: catalogd-system
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: catalogd-catalogserver
            port:
              number: 80
