apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterCatalog
metadata:
  name: operatorhubio
  namespace: olmv1-system
spec:
  source:
    type: Image
    image:
      ref: quay.io/operatorhubio/catalog:latest
      pollInterval: 10m
